---
title:"Assignment 1: Introduction"
author: "Yin-Chia Yang"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took a basic certificated class with python provided by my undergrad university's learning center, also was forced to learn java but didn't really excelled on that. Other than that, just the basic excel trainings, I am new to both R and Git. 

2. Are there any components of the course about which you feel confident?

> Answer: Hopefully with some understanding of other programing language could help to smooth the learning curve, and hopefully our microeconometric class last semester will be helpful to understand the statistics part.  

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel like we are in good hands, my only concern is I will have to get used to setting up my routine to finish the requirements.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/yangeline/EDA_Spring2024.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
